version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: fintech_mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
