services:
  mongodb:
    image: mongo:6.0
    container_name: fintech_mongodb
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend/Fintech.API
      dockerfile: dockerfile
    container_name: fintech-backend
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - "5001:8080"

  frontend:
    build:
      context: ./frontend/fintechapp
      dockerfile: dockerfile
    container_name: fintech-frontend
    ports:
      - "4200:80"
